name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - id: get-repo-values
        run: echo "url=https://gavincaul.github.io/exercisesite" >> $GITHUB_OUTPUT

      - name: Update package.json homepage
        uses: jossef/action-set-json-field@v1
        with:
          file: client/package.json
          field: homepage
          value: ${{ steps.get-repo-values.outputs.url }}

      - name: Install dependencies
        run: npm ci
        working-directory: client
        
      - name: Create GitHub redirect page
        run: |
          echo "<html><head><meta http-equiv='refresh' content='0; URL=${{github.server_url}}/${{github.repository}}' /></head><body>Redirecting to repository</body></html>" > client/public/github.html

      - name: Build app
        run: npm run build --if-present
        working-directory: client
        
      - name: Disable Jekyll on GitHub Pages
        run: echo "" > client/build/.nojekyll

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ env.user_name }}"
          git config --global user.email "${{ env.user_email }}"
          git remote set-url origin https://${{ env.github_token }}@github.com/${{ env.repository }}
          npm run predeploy
          npm run deploy
        working-directory: client
        env:
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          github_token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
